// Array of popular Indian destinations
const recommendations = [
    {
        id: 'tajmahal',
        name: 'Taj Mahal',
        location: 'Agra, Uttar Pradesh',
        description: 'This iconic ivory-white marble mausoleum is one of the most recognized structures in the world and India\'s most famous landmark, built by Emperor Shah Jahan in memory of his beloved wife.',
        image: 'images/tajmahal.jpg',
        alt: 'Taj Mahal - iconic marble mausoleum at sunrise with reflections',
        rating: 4.9,
        conditions: ['UNESCO World Heritage'],
        region: 'North India',
        state: 'Uttar Pradesh',
        slug: 'tajmahal'
    },
    {
        id: 'varanasi',
        name: 'Varanasi',
        location: 'Uttar Pradesh',
        description: 'One of the oldest continuously inhabited cities in the world, Varanasi is a spiritual hub where pilgrims come to bathe in the sacred Ganges River and perform funeral rites.',
        image: 'images/varanasi.jpg',
        alt: 'Varanasi ghats at dusk with religious ceremonies and floating candles',
        rating: 4.7,
        conditions: ['Spiritual'],
        region: 'North India',
        state: 'Uttar Pradesh',
        slug: 'varanasi'
    },
    {
        id: 'jaipur',
        name: 'Jaipur',
        location: 'Rajasthan',
        description: 'Known as the "Pink City" for its distinctive terracotta pink buildings, Jaipur is home to magnificent palaces, forts, and vibrant bazaars.',
        image: 'images/Jaipur.jpg',
        alt: 'Amber Fort in Jaipur with ornate architecture and scenic landscape',
        rating: 4.6,
        conditions: ['Heritage'],
        region: 'North India',
        state: 'Rajasthan',
        slug: 'jaipur'
    },
    {
        id: 'kerala',
        name: 'Kerala Backwaters',
        location: 'Kerala',
        description: 'A network of interconnected canals, rivers, lakes, and inlets formed by more than 900 km of waterways. Experience traditional houseboats and lush green landscapes.',
        image: 'images/Kerala Backwaters3.jpg',
        alt: 'Traditional houseboat on Kerala backwaters with palm trees at sunset',
        rating: 4.8,
        conditions: ['Nature'],
        region: 'South India',
        state: 'Kerala',
        slug: 'kerala'
    },
    {
        id: 'goa',
        name: 'Goa',
        location: 'Goa',
        description: 'India\'s smallest state is known for its beaches, nightlife, and unique blend of Indian and Portuguese cultures, visible in its architecture, food, and customs.',
        image: 'images/Goa.jpg',
        alt: 'Aerial view of Goa beach with palm trees and turquoise waters',
        rating: 4.5,
        conditions: ['Beaches'],
        region: 'West India',
        state: 'Goa',
        slug: 'goa'
    },
    {
        id: 'darjeeling',
        name: 'Darjeeling',
        location: 'West Bengal',
        description: 'This hill station in West Bengal is famous for its tea plantations, stunning views of the Himalayas, and the historic "Toy Train" — a UNESCO World Heritage railway.',
        image: 'images/Darjeeling.jpg',
        alt: 'Tea plantations in Darjeeling with Himalayan mountain views',
        rating: 4.6,
        conditions: ['Mountains'],
        region: 'East India',
        state: 'West Bengal',
        slug: 'darjeeling'
    },
    {
        id: 'hampi',
        name: 'Hampi',
        location: 'Karnataka',
        description: 'Explore the vast ruins of the Vijayanagara Empire, a UNESCO site with stunning temples, palaces, and unique boulder-strewn landscapes.',
        image: 'images/hampi.jpg',
        alt: 'Ancient stone temples and ruins of Hampi under a clear sky',
        rating: 4.8,
        conditions: ['UNESCO Site'],
        region: 'South India',
        state: 'Karnataka',
        slug: 'hampi'
    },
    {
        id: 'mysore',
        name: 'Mysore Palace',
        location: 'Karnataka',
        description: 'A historical palace and the official residence of the Wadiyar dynasty. Famous for its Indo-Saracenic architecture and stunning Dasara festival illumination.',
        image: 'images/mysore_palace.jpg',
        alt: 'Grand Mysore Palace illuminated at night',
        rating: 4.7,
        conditions: ['Royalty'],
        region: 'South India',
        state: 'Karnataka',
        slug: 'mysore'
    },
    {
        id: 'ladakh',
        name: 'Ladakh',
        location: 'Jammu & Kashmir',
        description: 'Known as "Little Tibet", Ladakh is famous for its remote mountain beauty, Buddhist monasteries, and pristine landscapes with high-altitude lakes.',
        image: 'images/ladakh.jpg',
        alt: 'Pangong Lake in Ladakh with mountains in the background',
        rating: 4.9,
        conditions: ['Adventure'],
        region: 'North India',
        state: 'Jammu & Kashmir',
        slug: 'ladakh'
    },
    {
        id: 'andaman',
        name: 'Andaman Islands',
        location: 'Andaman & Nicobar',
        description: 'This archipelago in the Bay of Bengal offers pristine beaches, coral reefs for diving and snorkeling, and lush tropical forests.',
        image: 'images/andaman.jpg',
        alt: 'Radhanagar Beach on Havelock Island with white sand and turquoise water',
        rating: 4.8,
        conditions: ['Islands'],
        region: 'East India',
        state: 'Andaman & Nicobar',
        slug: 'andaman'
    },
    {
        id: 'khajuraho',
        name: 'Khajuraho Temples',
        location: 'Madhya Pradesh',
        description: 'Famous for their Nagara-style architectural symbolism and erotic sculptures, these UNESCO World Heritage temples were built between 950 and 1050 CE.',
        image: 'images/khajuraho.jpg',
        alt: 'Ancient stone temples of Khajuraho with intricate carvings',
        rating: 4.7,
        conditions: ['UNESCO World Heritage'],
        region: 'Central India',
        state: 'Madhya Pradesh',
        slug: 'khajuraho'
    },
    {
        id: 'udaipur',
        name: 'Udaipur',
        location: 'Rajasthan',
        description: 'Known as the "City of Lakes" and the "Venice of the East", Udaipur is famous for its palaces, lakes, and romantic atmosphere.',
        image: 'images/udaipur.jpg',
        alt: 'Lake Palace in Udaipur surrounded by Lake Pichola',
        rating: 4.8,
        conditions: ['Romantic'],
        region: 'North India',
        state: 'Rajasthan',
        slug: 'udaipur'
    },
    {
        id: 'rann-of-kutch',
        name: 'Rann of Kutch',
        location: 'Gujarat',
        description: 'One of the largest salt deserts in the world, the White Rann transforms into a surreal landscape during full moon nights and hosts the vibrant Rann Utsav festival.',
        image: 'images/rann-of-kutch.jpg',
        alt: 'White salt desert of Rann of Kutch under moonlight',
        rating: 4.6,
        conditions: ['Unique Landscape'],
        region: 'West India',
        state: 'Gujarat',
        slug: 'rann-of-kutch'
    },
    {
        id: 'sundarbans',
        name: 'Sundarbans',
        location: 'West Bengal',
        description: 'The largest mangrove forest in the world and a UNESCO World Heritage Site, home to the Bengal tiger and numerous other species.',
        image: 'images/sundarbans.jpg',
        alt: 'Mangrove forest in Sundarbans with waterways',
        rating: 4.7,
        conditions: ['Wildlife'],
        region: 'East India',
        state: 'West Bengal',
        slug: 'sundarbans'
    },
    {
        id: 'ellora-ajanta',
        name: 'Ellora & Ajanta Caves',
        location: 'Maharashtra',
        description: 'These UNESCO World Heritage sites feature rock-cut cave monuments with paintings and sculptures considered masterpieces of Buddhist religious art.',
        image: 'images/ellora-ajanta.jpg',
        alt: 'Ancient rock-cut caves of Ellora with intricate carvings',
        rating: 4.8,
        conditions: ['UNESCO World Heritage'],
        region: 'West India',
        state: 'Maharashtra',
        slug: 'ellora-ajanta'
    },
    {
        id: 'munnar',
        name: 'Munnar',
        location: 'Kerala',
        description: 'A hill station in Kerala known for its tea plantations, rolling hills, and cool climate, making it a popular honeymoon destination.',
        image: 'images/munnar.jpg',
        alt: 'Tea plantations in Munnar with misty mountains',
        rating: 4.7,
        conditions: ['Hill Station'],
        region: 'South India',
        state: 'Kerala',
        slug: 'munnar'
    },
    {
        id: 'amritsar',
        name: 'Golden Temple',
        location: 'Punjab',
        description: 'The holiest gurdwara and the most important pilgrimage site of Sikhism, known for its golden architecture and the world\'s largest free community kitchen.',
        image: 'images/golden-temple.jpg',
        alt: 'Golden Temple in Amritsar illuminated at night with reflections in the sacred pool',
        rating: 4.9,
        conditions: ['Spiritual'],
        region: 'North India',
        state: 'Punjab',
        slug: 'amritsar'
    },
    {
        id: 'rishikesh',
        name: 'Rishikesh',
        location: 'Uttarakhand',
        description: 'Known as the "Yoga Capital of the World", Rishikesh is a spiritual center situated on the banks of the Ganges River, famous for yoga, meditation, and adventure sports.',
        image: 'images/rishikesh.jpg',
        alt: 'Laxman Jhula bridge over the Ganges River in Rishikesh',
        rating: 4.7,
        conditions: ['Spiritual'],
        region: 'North India',
        state: 'Uttarakhand',
        slug: 'rishikesh'
    }
];
